### ISSUE TITLE
help?

### ISSUE THREAD

**Issue by Poosi** [Solistor/NewStory#2]
![adfsgdf](https://user-images.githubusercontent.com/33558661/32679518-4e37d2da-c62c-11e7-94f1-5605e9b1cb1a.png)

**Comment by isyy** [comment]
the error is caused because sayori, natsuki, and yuri's parts haven't been scripted yet. be patient and hopefully the developer will finish it sometime!!

**Comment by Poosi** [comment]
Ah, alright. I just wasn't sure if it was something caused by something else. Thanks
